baseURL = "https://josef-reither-museum.at/"
languageCode = "de-AT"
title = "Josef Reither Museum"
theme = "ananke"
disableKinds = ["RSS"]
defaultContentLanguage = "de"

[markup.goldmark.renderer]
unsafe = true
